name: Lint and run unit tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"

      - name: Install golint
        run: GO111MODULE=off go get -u golang.org/x/lint/golint

      - name: Lint the codebase
        run: $(go env GOPATH)/bin/golint .

      - name: Run unit tests
        run: go test -v .
