name: Lint and run unit tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.34.1
          args: .

      - name: Run unit tests
        run: go test -v .
